services: 
  db: 
    image: postgres:15-alpine
    restart: always 
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - "${DB_PORT}:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  
  frontend: 
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes: 
      - ./app/frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile 
    ports: 
      - "3000:3000"
    volumes: 
      - ./app/backend:/app
      - /app/node_modules
    command: npm run start:dev 